spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/bugs?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
server:
  port: 9002

mybatis-plus:
  typeAliasesPackage: com.example.bugs.domain
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-field: active
      logic-delete-value: 0
      logic-not-delete-value: 1
      table-underline: true

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

