server:
  port: 8001
spring:
  application:
    name: CLOUD-PAYMENT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka/,http://eureka7002.cn:7002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: env,health,metrics,info,hystrix.stream