server:
  port: 8002
spring:
  application:
    name: CLOUD-PAYMENT-SERVICE
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 配置内容
eureka:
  instance:
    hostname: CLOUD-PAYMENT-SERVICE
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka/,http://eureka7002.cn:7002/eureka/