server:
  port: 9001
spring:
  application:
    name: CLOUD-NACOS-PAYMENT
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"