server:
  port: 3344
    # druid 配置内容
eureka:
  instance:
    hostname: CLOUD-CONFIG-CENTER
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka/,http://eureka7002.cn:7002/eureka/
spring:
  application:
    name: CLOUD-CONFIG-CENTER
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lu-yuan/spring-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: master
  rabbitmq:
    host: 192.168.123.203
    port: 5672
    username: guest
    password: guest

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'